version: '3.8'

services:
  cicd-generator-service:
    container_name: cicd-generator-container
    build:
      context: .
      dockerfile: src/CicdGeneratorService/Dockerfile
    ports:
      - "9090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
